### ISSUE TITLE
When will code become available?

### ISSUE THREAD

**Issue by mileseverett** [EIDOSLAB/towards-efficient-capsule-networks#1]
Hello

Looking to investigate the internals of your models, but the code is not available even though the paper says it is.

When will it be uploaded?

Thanks
Miles

**Comment by riccardorenzulli** [comment]
Hi!

The code will be published in the next days, for sure before ICIP 2022 will be held. I'm finishing some code cleaning and I'll upload it. Thanks for your interest!

**Comment by mileseverett** [comment]
Awesome thanks :) 

As a fellow capsule network researcher, I'd love to talk to you about your paper/capsule networks in general one day.

**Comment by riccardorenzulli** [comment]
The code is now available!

> As a fellow capsule network researcher, I'd love to talk to you about your paper/capsule networks in general one day.

It would be a pleasure! My email is riccardo.renzulli@edu.unito.it
